# ruff: noqa
"""User journeys: J1 on-call responder, J2 operator setup. Regenerate: python3 architecture/_gen/journeys.py"""

from __future__ import annotations

from pathlib import Path

from swimlane import Diagram, Step, render

OUT = Path(__file__).resolve().parent.parent / "journeys"

LEGEND = [
    ("human", "person"),
    ("port", "chat surface"),
    ("core", "Smokejumper"),
    ("audit", "audit / evidence"),
    ("gate", "approval-gated"),
    ("store", "ticket / record"),
    ("signal", "system signal"),
]

# ── J1 · on-call responder ─────────────────────────────────────────────────
J1 = Diagram(
    title="J1 — On-call responder: from page to closed ticket without leaving Slack",
    subtitle="One incident, one Slack thread. The responder reads, decides, approves. Smokejumper witnesses, reasons, files, and proves. Times are the design target for a high-severity alert.",
    lanes=[
        "Responder\n(on-call)",
        "Slack thread\n(root card + replies)",
        "Smokejumper\n(agents · workflows)",
        "Witnesses\n(MCP servers)",
        "Ticket &\nFlight Recorder",
    ],
    columns=[
        "t+0 · alert",
        "t+5s · admitted",
        "t+10s · triage",
        "t+1m · investigate",
        "t+2m · verify",
        "t+3m · conclude",
        "t+4m · decide",
        "t+6m · mitigate",
        "t+15m · resolve",
        "later · learn",
    ],
    steps=[
        Step(
            3,
            0,
            "Alertmanager fires",
            ["HighErrorRate api p99 5xx", "posts webhook v4 batch"],
            "signal",
        ),
        Step(
            2,
            1,
            "admit · dedupe · enqueue",
            ["verify token · normalize B2", "fingerprint → run_id", "202 to Alertmanager"],
            "core",
            badge="B8 event",
        ),
        Step(
            1,
            1,
            "root card created",
            [
                "“Investigating: HighErrorRate api”",
                "scope: high → ≤8 agents · $ cap",
                "checklist: triage ▸ investigate ▸ verify",
            ],
            "port",
        ),
        Step(
            2,
            2,
            "triage agents ∥",
            [
                "impact: 3.1% of req/min (n=42k)",
                "severity: SEV2 by rubric",
                "owner: team-payments on call",
            ],
            "core",
            badge="B11",
        ),
        Step(
            1,
            2,
            "card edited in place",
            ["impact + SEV + owner lines appear", "no new posts — checklist ticks"],
            "port",
        ),
        Step(
            2,
            3,
            "investigate agents ∥",
            [
                "change-correlator · saturation-finder",
                "error-signature-summarizer",
                "precedent-researcher",
            ],
            "core",
            badge="B4 → MCP",
        ),
        Step(
            3,
            3,
            "witness reads",
            [
                "mcp-grafana: query_prometheus",
                "github-mcp: deployments",
                "k8s-mcp: events (read-only)",
            ],
            "port",
            badge="EvidenceRecord",
        ),
        Step(
            4,
            3,
            "evidence snapshots",
            ["E1 deploy #412 t−4m", "E2 pool_wait p99 ↑", "E3 signature first seen svc/api"],
            "audit",
        ),
        Step(
            2,
            4,
            "verify gate",
            [
                "adversarial-verifier: disproof tried",
                "temporal-order: cause < effect ✓",
                "H1 validated · H2 invalidated",
            ],
            "core",
            badge="hypothesis",
        ),
        Step(
            1,
            4,
            "thread reply: findings",
            [
                "H1 ✓ deploy #412 4m before onset [E1][E3]",
                "H2 ✗ no saturation [E2]",
                "14 tool calls · 3 sources · View steps",
            ],
            "port",
        ),
        Step(
            2,
            5,
            "synthesize B6",
            [
                "verdict: root_caused · confidence 0.86",
                "proposed: rollback #412 (reversible)",
                "tokens 41k · $0.31",
            ],
            "core",
            badge="B6",
        ),
        Step(
            4,
            5,
            "ticket opened",
            ["Linear PAY-1187 via MCP", "B6 summary + Source chips", "run closed · byte range"],
            "store",
            badge="B8 action",
        ),
        Step(
            1,
            5,
            "conclusion reply",
            ["verdict + top hypothesis + citations", "buttons: Approve rollback · Deny · Ask"],
            "port",
        ),
        Step(
            0,
            6,
            "reads, decides",
            ["opens Source 1 and Source 3", "clicks Approve rollback"],
            "human",
        ),
        Step(
            2,
            6,
            "approval consumed once",
            [
                "B5 token bound to tool call sha",
                "double-click → one consumption",
                "graph resumes from interrupt",
            ],
            "gate",
            badge="B5",
        ),
        Step(
            2,
            7,
            "rollback-executor (ACT)",
            [
                "privileged tier · serialized",
                "argocd rollback (change source)",
                "mitigation-verifier pre/post",
            ],
            "gate",
            badge="act",
        ),
        Step(
            3,
            7,
            "post-action reads",
            ["5xx rate 3.1% → 0.2% in 90s", "pool_wait back to baseline"],
            "port",
        ),
        Step(
            1,
            7,
            "thread reply: mitigated",
            ["“rollback applied · verified ✓ [E4]”", "status: mitigated (verified)"],
            "port",
        ),
        Step(
            2,
            8,
            "recovery-confirmer",
            ["queues drained · retries settled", "AM resolved → window closed"],
            "core",
        ),
        Step(
            4,
            8,
            "ticket updated",
            ["PAY-1187: mitigated · resolved", "(fingerprint, run_id) idempotent"],
            "store",
        ),
        Step(
            0,
            8,
            "reads resolution",
            ["“Was this the cause?” → Yes", "human verdict recorded"],
            "human",
            badge="feedback",
        ),
        Step(
            2,
            9,
            "learn agents (scheduled)",
            [
                "postmortem-drafter · factors",
                "action-item-gate on follow-ups",
                "case → episode (post-v1)",
            ],
            "core",
        ),
        Step(
            4,
            9,
            "replay proves it",
            ["smokejumper replay <run_id>", "same B6 from snapshots offline"],
            "audit",
        ),
    ],
    edges=[
        (0, 1, "B1"),
        (1, 2, None),
        (1, 3, None),
        (3, 4, None),
        (3, 5, None),
        (5, 6, None),
        (6, 7, None),
        (5, 8, None),
        (8, 9, None),
        (8, 10, None),
        (10, 11, None),
        (10, 12, None),
        (12, 13, None),
        (13, 14, "approve"),
        (14, 15, None),
        (15, 16, None),
        (16, 17, None),
        (15, 18, None),
        (18, 19, None),
        (18, 20, None),
        (18, 21, None),
        (21, 22, None),
    ],
    footer=[
        "What the responder never does: open Grafana, grep logs, find the deploy, or write the ticket. What the responder always does: read three citations and press one button.",
        "Every card in lanes 3–5 is one or more B8 lines; ‘View steps’ opens the full ledger (see system/c3-components.svg, step ledger). Cards in lane 2 are the ONLY Slack posts — one root card edited in place plus four thread replies.",
        "Design targets, not measurements: t+3m to a cited conclusion on a high-severity alert; t+6m mitigated when a reversible action exists and a human approves.",
    ],
    legend=LEGEND,
    col_w=214,
    card_w=202,
)

# ── J2 · operator setup ────────────────────────────────────────────────────
J2 = Diagram(
    title="J2 — Operator setup: from clone to first investigated alert in about 30 minutes",
    subtitle="The whole point of adopting official SDKs and existing MCP servers: five credentials, no public URL, no tunnel. Counted against the vendor docs read on 2026-08-29.",
    lanes=[
        "Operator",
        "Terminal /\ncompose",
        "Slack app\n(manifest)",
        "Alert source\n(Alertmanager / Datadog)",
        "MCP servers\n(witnesses)",
    ],
    columns=["0–3 min", "3–6 min", "6–12 min", "12–18 min", "18–24 min", "24–30 min", "verify"],
    steps=[
        Step(0, 0, "clone · cp .env.example .env", ["fill nothing yet", "uv sync"], "human"),
        Step(
            1,
            0,
            "docker compose up -d --build",
            ["postgres+pgvector · redis · app", "alembic upgrade head at boot"],
            "core",
        ),
        Step(
            1,
            1,
            "curl /healthz → 200",
            ["postgres ok · schema head · redis ok", "worker ok · outbox ok"],
            "core",
            badge="proof",
        ),
        Step(
            0,
            1,
            "smokejumper check-config",
            ["local env · stubs allowed", "prod refuses stubs — by design"],
            "human",
        ),
        Step(
            2,
            2,
            "Slack app from manifest.json",
            [
                "scopes: app_mentions:read chat:write",
                "channels:history reactions:write",
                "Socket Mode + Interactivity ON",
            ],
            "port",
            badge="8 steps",
        ),
        Step(
            2,
            3,
            "two tokens → .env",
            [
                "xapp-… app token (connections:write)",
                "xoxb-… bot token after install",
                "no public URL · no ngrok",
            ],
            "port",
            badge="2 creds",
        ),
        Step(
            0,
            3,
            "invite bot to #incidents",
            ["/invite @smokejumper", "SLACK_CHANNEL_ID → .env"],
            "human",
        ),
        Step(
            3,
            4,
            "point the alert source at us",
            [
                "Alertmanager receiver → /webhooks/alertmanager",
                "  peer CIDR allowlist (no credential)",
                "Datadog: webhook + X-Smokejumper-Token",
            ],
            "signal",
            badge="1 secret",
        ),
        Step(
            4,
            4,
            "witness credentials",
            [
                "GRAFANA_SERVICE_ACCOUNT_TOKEN",
                "(optional) Datadog api/app keys",
                "k8s-mcp --read-only via kubeconfig",
            ],
            "port",
            badge="1–2 creds",
        ),
        Step(
            1,
            5,
            "compose up --profile witness",
            [
                "mcp-grafana sidecar · k8s-mcp sidecar",
                "manifest.yaml: every tool tiered",
                "boot fails on untiered tool",
            ],
            "core",
        ),
        Step(
            1,
            6,
            "fixtures replay --source alertmanager",
            ["202 · one run · one fixture ticket", "GET /runs/{fp} → B6 + audit range"],
            "core",
            badge="proof",
        ),
        Step(
            2,
            6,
            "first thread appears",
            ["root card + triage lines", "reply with citations"],
            "port",
        ),
        Step(
            0,
            6,
            "operator reads the thread",
            ["@smokejumper what did you rule out?", "→ hypothesis board reply"],
            "human",
        ),
    ],
    edges=[
        (0, 1, None),
        (1, 2, None),
        (2, 3, None),
        (3, 4, None),
        (4, 5, None),
        (5, 6, None),
        (6, 7, None),
        (7, 8, None),
        (8, 9, None),
        (9, 10, None),
        (10, 11, None),
        (11, 12, None),
    ],
    footer=[
        "Credential count for the minimum path (Slack + Alertmanager + Grafana): 4 — xapp, xoxb, Grafana service-account token, and the Alertmanager peer CIDR (not a secret). Datadog adds one webhook token; Linear MCP adds one API key or OAuth.",
        "Three proofs on the way, each a command with a checkable output: /healthz 200 · check-config exit 0 · fixtures replay → GET /runs/{fp}. Nothing here is ‘it should work’.",
        "Facts behind the counts: Slack Socket Mode quickstart (docs.slack.dev), mcp-grafana README, kubernetes-mcp-server README — see docs/plans/2026-08-29-reference-architecture-analysis.md §5.",
    ],
    legend=LEGEND,
)

if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    render(J1, OUT / "j1-oncall-responder.svg")
    render(J2, OUT / "j2-operator-setup.svg")
    print("ok")
