# ruff: noqa
"""Incident scenarios S1–S4, grounded in public postmortems (docs/plans/2026-08-29-incident-scenarios-research.md).
Regenerate: python3 architecture/_gen/scenarios.py"""

from __future__ import annotations

from pathlib import Path

from swimlane import Diagram, Step, render

OUT = Path(__file__).resolve().parent.parent / "scenarios"

LANES = [
    "System signals\n(causal chain)",
    "First human\nsignal",
    "Smokejumper\nhypotheses",
    "Evidence that\ndecides",
    "Mitigation\nladder",
    "Responder",
]
LEGEND = [
    ("signal", "system signal"),
    ("port", "alert / chat"),
    ("core", "hypothesis held"),
    ("ok", "validated"),
    ("audit", "evidence snapshot"),
    ("gate", "action (approval)"),
    ("human", "person"),
]
COLS = [
    "hours before",
    "T0 · trigger",
    "T+min · symptom",
    "detect",
    "triage",
    "investigate",
    "verify",
    "mitigate",
    "resolve",
]

S1 = Diagram(
    title="S1 — API 5xx from database I/O saturation (gp2 burst-balance / IOPS ceiling)",
    subtitle="The slow-burn cause hidden behind an application symptom. Mechanism from AWS RDS metric definitions (READ); timeline shape from Honeycomb 2023, GitLab 2026, Grafana Labs — no first-party postmortem names BurstBalance with minutes; say so.",
    lanes=LANES,
    columns=COLS,
    steps=[
        Step(
            0,
            0,
            "BurstBalance declining",
            [
                "EBSIOBalance% / EBSByteBalance% ↓ 10–12 h",
                "nobody alerts on a leading indicator",
                "(Chen 2025: dropped for 10–12 h before)",
            ],
            "signal",
            badge="leading",
        ),
        Step(
            0,
            1,
            "IOPS hits ceiling",
            [
                "ReadIOPS+WriteIOPS flat at 3×GiB (min 100)",
                "BurstBalance → 0",
                "DiskQueueDepth rises",
            ],
            "signal",
            badge="T0",
        ),
        Step(
            0,
            2,
            "latency → pool → 5xx",
            [
                "ReadLatency ms → 100s ms",
                "pg wait_event IO:DataFileRead",
                "DatabaseConnections → cap · pool wait ↑",
                "504 (LB) · 503 (health) · 500 (driver)",
            ],
            "signal",
        ),
        Step(
            1,
            3,
            "HighErrorRate api",
            [
                "synthetic / SLO alert, not the cause metric",
                "Honeycomb: SLO burn dismissed overnight",
                "→ webhook v4 → Smokejumper",
            ],
            "port",
            badge="B1",
        ),
        Step(
            2,
            4,
            "hypotheses seeded",
            [
                "H1 storage credit exhaustion",
                "H2 single bad query / plan flip",
                "H3 lock queue · H4 connection storm",
                "H5 T-class CPU credits",
            ],
            "core",
            badge="board",
        ),
        Step(
            5,
            4,
            "sees root card",
            ["impact 4.2% of req (n=61k) · SEV2", "owner: platform-db", "checklist ticking"],
            "human",
        ),
        Step(
            3,
            5,
            "witness reads (∥)",
            [
                "CW: BurstBalance=0 · IOPS flat · latency ×40",
                "pg_stat_statements: uniform, no single query",
                "pg_locks not granted = 0",
                "change.list: no deploy in window",
            ],
            "audit",
            badge="E1–E4",
        ),
        Step(
            2,
            5,
            "board updates",
            [
                "H1 ✓ validated (E1 all three conditions)",
                "H2 ✗ (E2 uniform) · H3 ✗ (E3)",
                "H4 ✗ ordering: IO first · H5 n/a class",
            ],
            "ok",
        ),
        Step(
            3,
            6,
            "disproof attempted",
            [
                "is IO latency up with balance > 20%? no",
                "connections before IO? no (E4 order)",
                "order: balance→IOPS→latency→conns→5xx ✓",
            ],
            "audit",
            badge="verify",
        ),
        Step(
            2,
            6,
            "B6 root_caused 0.84",
            [
                "cause: gp2 credits exhausted on db-main",
                "red herring named: CPU looked hot (Chen)",
                "Source chips [1][2][3][4]",
            ],
            "ok",
            badge="B6",
        ),
        Step(
            4,
            7,
            "ladder (reversible first)",
            [
                "1 shed load / circuit-break (Honeycomb)",
                "2 cancel worst statements · ANALYZE",
                "3 failover to replica",
                "4 gp2 → gp3 3,000 IOPS (one-way, online)",
                "5 scale class (restart)",
            ],
            "gate",
            badge="proposed",
        ),
        Step(
            5,
            7,
            "approves 1 then 4",
            ["reads E1 chart · approves shed", "approves storage change (B5)"],
            "human",
            badge="B5",
        ),
        Step(
            3,
            7,
            "mitigation-verifier",
            ["DiskQueueDepth ↓ · latency ↓ in 4 min", "5xx 4.2% → 0.3%"],
            "audit",
        ),
        Step(
            0,
            8,
            "recovery confirmed",
            ["pool drained · retries settled", "AM resolved → window closed"],
            "signal",
        ),
        Step(
            4,
            8,
            "ticket + prevent",
            [
                "Linear DB-… mitigated · resolved",
                "expiry-forecaster: BurstBalance < 30% alert",
                "postmortem: indicator visible for 10 h",
            ],
            "gate",
        ),
    ],
    edges=[
        (0, 1, None),
        (1, 2, None),
        (2, 3, None),
        (3, 4, None),
        (4, 5, None),
        (4, 6, None),
        (6, 7, None),
        (7, 8, None),
        (8, 9, None),
        (9, 10, None),
        (10, 11, None),
        (11, 12, None),
        (12, 13, None),
        (13, 14, None),
    ],
    footer=[
        "Discriminating queries: CloudWatch BurstBalance · EBSIOBalance% · ReadIOPS/WriteIOPS · ReadLatency · DiskQueueDepth · DatabaseConnections · CPUCreditBalance ‖ SQL: pg_stat_activity wait_event grouping · pg_stat_statements by total_exec_time · pg_locks NOT granted ‖ PromQL: 5xx ratio · p99 · hikaricp_connections_pending.",
        "Grounding: AWS RDS metric reference (READ) · Honeycomb ‘RDS clogs & cache-refresh crash loops’ 2023, 68 min (READ) · GitLab INC 2026-08-27 plan flip → 500s, fixed by ANALYZE (READ) · Grafana Labs unbounded join, 28 min human vs 8 min assistant (READ) · Chen RDS gp2 burst post 2025 (INFERRED, page blocked).",
        "Open: no first-party postmortem names BurstBalance with a minute timeline — next probe is GitLab gl-infra ‘disk util|iops’ and SRE Weekly ‘burst balance’. Why it matters to Smokejumper: none of the four surveyed products publishes an IOPS example; the leading indicator is the open lane.",
    ],
    legend=LEGEND,
    col_w=262,
    card_w=248,
)

S2 = Diagram(
    title="S2 — Bad deploy or config change → error spike → rollback",
    subtitle="The most common cause in public postmortems and the fastest to fix when a discrete change exists. Timelines: Cloudflare 2019 (detect→mitigate 22 min, mitigate→recover 2 min), GitHub Aug-2024 (36 min), incident.io Jul-2024 (rollback re-deployed by pipeline).",
    lanes=LANES,
    columns=COLS,
    steps=[
        Step(
            0,
            0,
            "quiet baseline",
            ["RPS flat · 5xx 0.1%", "no leading indicator — that is the point"],
            "signal",
        ),
        Step(
            0,
            1,
            "deploy / config marker",
            [
                "CI deploy #412 · observed_generation ↑",
                "or config edit with no code deploy",
                "(Cloudflare 2025: permission → doubled file)",
            ],
            "signal",
            badge="T0",
        ),
        Step(
            0,
            2,
            "step-change in errors",
            [
                "5xx within 1–15 min of marker",
                "CPU pinned (2019) or panic/crash-loop (2025)",
                "errors segregate by version label",
            ],
            "signal",
        ),
        Step(
            1,
            3,
            "synthetic check pages",
            [
                "Cloudflare 2019: PagerDuty at T0+3m",
                "GitHub Aug-24: impact detected at +3m",
                "→ webhook → Smokejumper",
            ],
            "port",
            badge="B1",
        ),
        Step(
            2,
            4,
            "hypotheses seeded",
            [
                "H1 the change at T0",
                "H2 attack / traffic surge (red herring ×3)",
                "H3 dependency outage (S4)",
                "H4 artifact drift · H5 rollback didn't take",
            ],
            "core",
            badge="board",
        ),
        Step(
            5, 4, "sees root card", ["impact 3.1% (n=42k) · SEV2", "owner: team-payments"], "human"
        ),
        Step(
            3,
            5,
            "witness reads (∥)",
            [
                "change.list: deploy #412 at T0−4m (E1)",
                "5xx by version: new 9.8% · old 0.1% (E2)",
                "RPS flat, unique IPs flat (E3)",
                "dependency p99 unchanged (E4)",
            ],
            "audit",
            badge="E1–E4",
        ),
        Step(
            2,
            5,
            "board updates",
            [
                "H1 ✓ (E1+E2 segregation)",
                "H2 ✗ flat traffic (E3) — red herring named",
                "H3 ✗ (E4) · H4 open until artifact hash read",
            ],
            "ok",
        ),
        Step(
            3,
            6,
            "disproof attempted",
            [
                "errors on old version too? no (E2)",
                "onset before marker? no (E1 order)",
                "canary vs baseline confirms",
            ],
            "audit",
            badge="verify",
        ),
        Step(
            2,
            6,
            "B6 root_caused 0.91",
            [
                "cause: deploy #412 · commit abc123",
                "proposed: rollback (reversible)",
                "Source chips [1][2][3]",
            ],
            "ok",
            badge="B6",
        ),
        Step(
            4,
            7,
            "ladder",
            [
                "1 kill switch / flag off (CF 2019: 2 min)",
                "2 roll back artifact/config to known-good",
                "3 roll back code · VERIFY fleet version",
                "4 restart to flush state · 5 forward-fix last",
            ],
            "gate",
            badge="proposed",
        ),
        Step(
            5, 7, "approves rollback", ["one button · B5 token consumed once"], "human", badge="B5"
        ),
        Step(
            3,
            7,
            "mitigation-verifier",
            [
                "fleet version = old? (incident.io: pipeline re-deployed it)",
                "5xx 3.1% → 0.2% in 90 s",
            ],
            "audit",
        ),
        Step(0, 8, "recovery confirmed", ["error rate baseline · queues drained"], "signal"),
        Step(
            4,
            8,
            "ticket + prevent",
            [
                "ticket: mitigated → resolved",
                "action: pipeline must not re-apply revert",
                "episode saved for precedent-researcher",
            ],
            "gate",
        ),
    ],
    edges=[
        (0, 1, None),
        (1, 2, None),
        (2, 3, None),
        (3, 4, None),
        (4, 5, None),
        (4, 6, None),
        (6, 7, None),
        (7, 8, None),
        (8, 9, None),
        (9, 10, None),
        (10, 11, None),
        (11, 12, None),
        (12, 13, None),
        (13, 14, None),
    ],
    footer=[
        "Discriminating queries: deploy list / kubectl rollout history / flag audit ‖ PromQL: sum by(version)(rate(5xx)) / sum by(version)(rate(all)) · changes(kube_deployment_status_observed_generation[30m]) · increase(container_restarts[10m]) · sum(rate(http_requests_total[1m])) flat ⇒ not attack ‖ logs: panic|unwrap|FATAL.",
        "Grounding (all READ): Cloudflare 2019-07-02 WAF regex — 13:42 deploy · 13:45 page · 14:07 kill · 14:09 recovered; attack suspected first · Cloudflare 2025-11-18 Bot Mgmt file — 126 min to identify, DDoS red herring · GitHub 2024-08-14 config revert 36 min · GitHub 2024-03-15 framework upgrade rollback 42 min · incident.io 2024-07-09 pipeline re-deployed the reverted change.",
        "Why it matters to Smokejumper: change-correlator is the highest-yield question in the public record (config + deploy ≈ 65 of ~200 danluu postmortems); the verifier must check the fleet version AFTER rollback, not the rollback command's exit code.",
    ],
    legend=LEGEND,
    col_w=262,
    card_w=248,
)

S3 = Diagram(
    title="S3 — Connection / thread-pool exhaustion (traffic surge, slow downstream, N+1, lock queue)",
    subtitle="Tests saturation-finder vs change-correlator disambiguation. The discriminating metric — pool WAIT time — was uninstrumented in almost every postmortem read (incident.io found a 20 s wait only by monkey-patching database/sql).",
    lanes=LANES,
    columns=COLS,
    steps=[
        Step(
            0,
            0,
            "trigger accumulates",
            [
                "cache flush (Slack 22) · migration lock (Heroku)",
                "N+1 join (incident.io) · pool shrink (CircleCI)",
                "or plain traffic surge",
            ],
            "signal",
            badge="varies",
        ),
        Step(
            0,
            1,
            "per-request hold time ↑",
            ["pg_locks not granted (locks) or", "queries/request ×N (N+1) or", "slow IO (→ S1)"],
            "signal",
            badge="T0",
        ),
        Step(
            0,
            2,
            "pool → cap → 5xx",
            [
                "pool in-use = max · pool wait appears",
                "pgbouncer cl_waiting ↑ · FATAL too many conns",
                "threads block → health fails → 502/503/504",
                "‘context canceled’ in logs",
            ],
            "signal",
        ),
        Step(
            1,
            3,
            "customer report / Sentry",
            [
                "incident.io 2023: customer + Sentry flurry",
                "GitLab 2023: Apdex SLO + DB saturation",
                "Slack 2020: DB alert → 503s hours later",
            ],
            "port",
            badge="B1",
        ),
        Step(
            2,
            4,
            "hypotheses seeded",
            [
                "H1 lock queue · H2 slow query / bad plan",
                "H3 many small holds · N+1 · needless txn",
                "H4 pool config regression",
                "H5 downstream / IO slow (→ S1/S4)",
            ],
            "core",
            badge="board",
        ),
        Step(
            5,
            4,
            "sees root card",
            ["impact: 12% of API req (n=88k) · SEV2", "owner: core-api"],
            "human",
        ),
        Step(
            3,
            5,
            "witness reads (∥)",
            [
                "pg_locks not granted: 0 (E1)",
                "pg_stat_statements: all fast, ×7 per req (E2)",
                "traces: 7 DB spans/req since #390 (E3)",
                "pool pending p99 18 s (E4) · DB CPU 30% (E5)",
            ],
            "audit",
            badge="E1–E5",
        ),
        Step(
            2,
            5,
            "board updates",
            [
                "H1 ✗ (E1) · H2 ✗ (E2 fast) · H5 ✗ (E5 idle DB)",
                "H3 ✓ N+1 introduced by #390 (E2+E3)",
                "H4 open: pool cap unchanged? read config",
            ],
            "ok",
        ),
        Step(
            3,
            6,
            "disproof attempted",
            [
                "wait high while DB idle? yes (E4+E5) → not DB",
                "did span count rise at #390? yes (E3)",
                "red herring named: ‘scale up’ (Slack 2020)",
            ],
            "audit",
            badge="verify",
        ),
        Step(
            2,
            6,
            "B6 root_caused 0.79",
            [
                "cause: N+1 from #390 holding connections",
                "note: pool wait is the metric to alert on",
                "Source chips [2][3][4]",
            ],
            "ok",
            badge="B6",
        ),
        Step(
            4,
            7,
            "ladder",
            [
                "1 throttle / shed inbound (Slack boot throttle)",
                "2 cancel blocker pid (locks) — n/a here",
                "3 disable flag / job class (GitLab)",
                "4 rollback #390 · 5 rolling restart",
                "6 raise pool caps — usually worsens; last",
            ],
            "gate",
            badge="proposed",
        ),
        Step(
            5,
            7,
            "approves 1 + 4",
            ["shed first, then rollback", "declines ‘raise max_connections’"],
            "human",
            badge="B5",
        ),
        Step(
            3,
            7,
            "mitigation-verifier",
            ["pending p99 18 s → 40 ms", "5xx 12% → 0.4% · DB conns 200 → 60"],
            "audit",
        ),
        Step(
            0,
            8,
            "recovery confirmed",
            ["pool drained · no idle-in-transaction", "retries settled (metastable loop broken)"],
            "signal",
        ),
        Step(
            4,
            8,
            "ticket + prevent",
            [
                "ticket mitigated → resolved",
                "action: instrument pool wait; alert on it",
                "runbook: no pool-cap raise before diagnosis",
            ],
            "gate",
        ),
    ],
    edges=[
        (0, 1, None),
        (1, 2, None),
        (2, 3, None),
        (3, 4, None),
        (4, 5, None),
        (4, 6, None),
        (6, 7, None),
        (7, 8, None),
        (8, 9, None),
        (9, 10, None),
        (10, 11, None),
        (11, 12, None),
        (12, 13, None),
        (13, 14, None),
    ],
    footer=[
        "Discriminating queries: SQL pg_stat_activity by wait_event · blocked/blocking pg_locks join · pgbouncer SHOW POOLS (cl_waiting, maxwait) ‖ PromQL: hikaricp_connections_pending · go_sql_wait_duration_seconds_total · pgbouncer_pools_client_waiting_connections · idle-in-transaction count · per-trace DB span count.",
        "Grounding (all READ): incident.io 2023 ‘database-performance’ — 2 weeks, 24 deploys, cause = needless transaction on Slack modal · incident.io 2023 ‘clouds, caches, connections’ — N+1 → anetd CPU · Slack 2020-05-12 HAProxy slots, scale-up ‘didn’t help at all’ · Slack 2022-02-22 Vitess scatter, metastable · Heroku lock-queue gist 25 min · GitLab 2023-10-30 48 min · CircleCI JVM pool shrink · incident.io PGAudit restart.",
        "Why it matters to Smokejumper: the verifier must separate ‘DB is slow’ from ‘DB is idle but the app holds connections’ — E4+E5 together. Resolve and Cleric both centre ‘pool at 9x%’ as the clincher; the pool WAIT metric is sharper and rarer.",
    ],
    legend=LEGEND,
    col_w=262,
    card_w=248,
)

S4 = Diagram(
    title="S4 — Upstream dependency, certificate or DNS expiry (vendor fault)",
    subtitle="Tests ‘ours or theirs’ and the not_actionable verdict. AWS us-east-1 Oct-2025 (50 min to root cause), Cloudflare 1.1.1.1 Jul-2025 (9-min detection gap, BGP hijack red herring), Google Voice 2021 cert (only NEW connections failed).",
    lanes=LANES,
    columns=COLS,
    steps=[
        Step(
            0,
            0,
            "expiry approaching",
            ["cert notAfter in 30 d (blackbox probe)", "or nothing — vendor change is invisible"],
            "signal",
            badge="leading?",
        ),
        Step(
            0,
            1,
            "vendor change at T0",
            [
                "cert expires · DNS removed · prefix withdrawn",
                "ZERO internal deploy markers",
                "(AWS: DNS Enactor race removed all IPs)",
            ],
            "signal",
            badge="T0",
        ),
        Step(
            0,
            2,
            "new connections fail",
            [
                "keep-alives survive → errors RAMP, not step",
                "x509 expired · ENOTFOUND · connect timeout",
                "all callers of that host fail at once",
                "retries amplify (Epic launcher surge)",
            ],
            "signal",
        ),
        Step(
            1,
            3,
            "outbound error alert",
            [
                "DependencyErrorRate payments-processor",
                "vendor status page lags 20–40 min",
                "→ webhook → Smokejumper",
            ],
            "port",
            badge="B1",
        ),
        Step(
            2,
            4,
            "hypotheses seeded",
            [
                "H1 vendor endpoint down / unresolvable",
                "H2 cert expired (theirs or ours)",
                "H3 our egress / resolver / SG",
                "H4 our own deploy (S2) · H5 vendor rate limit",
            ],
            "core",
            badge="board",
        ),
        Step(
            5,
            4,
            "sees root card",
            ["impact: 100% of card auths (n=9.4k/min)", "SEV1 · owner: payments"],
            "human",
        ),
        Step(
            3,
            5,
            "witness reads (∥)",
            [
                "change.list: zero deploys/flags (E1)",
                "dig from 2 resolvers: NXDOMAIN (E2)",
                "openssl s_client: n/a — no resolution (E3)",
                "vendor status page ‘investigating’ (E4)",
                "errors from all AZs, not one (E5)",
            ],
            "audit",
            badge="E1–E5",
        ),
        Step(
            2,
            5,
            "board updates",
            [
                "H1 ✓ (E2+E5) · H2 blocked (E3) · H3 ✗ (E5)",
                "H4 ✗ (E1) · H5 ✗ (connect errors, not 429)",
                "red herring named: BGP hijack / DDoS",
            ],
            "ok",
        ),
        Step(
            3,
            6,
            "disproof attempted",
            [
                "resolves from external vantage? no",
                "did anything of ours change? no (E1)",
                "→ verdict: theirs",
            ],
            "audit",
            badge="verify",
        ),
        Step(
            2,
            6,
            "B6 not_actionable · 0.88",
            [
                "cause: vendor DNS for api.processor.example",
                "nothing to fix here; mitigate impact only",
                "Source chips [1][2][4][5]",
            ],
            "ok",
            badge="B6",
        ),
        Step(
            4,
            7,
            "ladder",
            [
                "1 fail open: flag off dependent feature",
                "2 route around: 2nd processor · pinned IP",
                "3 renew cert if OURS (Epic 37 min) — n/a",
                "4 widen timeouts · retry budgets",
                "5 wait on vendor; freeze autoscaling",
            ],
            "gate",
            badge="proposed",
        ),
        Step(
            5,
            7,
            "approves 1 + 4",
            ["flag off · retry budget", "posts status-page draft (C3) after review"],
            "human",
            badge="B5",
        ),
        Step(
            3,
            7,
            "mitigation-verifier",
            [
                "auth failures 100% → 0% via fallback path",
                "vendor still down — impact mitigated only",
            ],
            "audit",
        ),
        Step(
            0,
            8,
            "vendor recovers",
            ["dig resolves · handshake ok", "pools recycle · error rate → 0"],
            "signal",
        ),
        Step(
            4,
            8,
            "ticket + prevent",
            [
                "ticket: not_actionable · mitigated",
                "stakeholder-notifier: contract SLA clock",
                "expiry-forecaster: alert on cert < 30 d",
            ],
            "gate",
        ),
    ],
    edges=[
        (0, 1, None),
        (1, 2, None),
        (2, 3, None),
        (3, 4, None),
        (4, 5, None),
        (4, 6, None),
        (6, 7, None),
        (7, 8, None),
        (8, 9, None),
        (9, 10, None),
        (10, 11, None),
        (11, 12, None),
        (12, 13, None),
        (13, 14, None),
    ],
    footer=[
        'Discriminating queries: dig +short host @1.1.1.1 / @8.8.8.8 · openssl s_client … | x509 -noout -dates · curl -sv from ≥2 regions ‖ PromQL: probe_ssl_earliest_cert_expiry − time() · probe_success · sum by(host)(rate(http_client_requests{status=~"5..|0"})) · dns_lookup_failures ‖ logs: x509|certificate has expired|ENOTFOUND|EAI_AGAIN ‖ change events: confirm ZERO.',
        "Grounding: AWS us-east-1 2025-10-19 DynamoDB DNS — 23:48 onset · 00:38 root cause · 02:25 DNS restored (READ) · Cloudflare 1.1.1.1 2025-07-14 — 21:48 withdraw · 22:01 alert · 22:20 revert · 22:54 restored; BGP hijack unrelated (READ) · Google Voice 2021 cert 4 h 22 min, new SIP only (READ via report) · Epic 2021 wildcard cert 37 min (INFERRED) · incident.io 2025-10-20 hit via transitive vendors (READ via summary).",
        "Why it matters to Smokejumper: this is the only scenario whose correct verdict is NOT root_caused — `not_actionable` must exist in B6 (it does not today; see reference-architecture-analysis §4). The unit of failure is the transitive dependency, not the named vendor.",
    ],
    legend=LEGEND,
    col_w=262,
    card_w=248,
)

if __name__ == "__main__":
    OUT.mkdir(exist_ok=True)
    for name, d in (
        ("s1-db-iops-saturation", S1),
        ("s2-bad-deploy-rollback", S2),
        ("s3-connection-pool-exhaustion", S3),
        ("s4-upstream-dependency-outage", S4),
    ):
        render(d, OUT / f"{name}.svg")
    print("ok")
